Repository team5985/DeepSpace, pull requests merged in 2019-01, with the labels that each got.

#24 Heading Assist Code
  DeepSpace/src/main/java/frc/robot/subsystems/Drive.java
Labels: Automated, drivetrain, enhancement

#25 Reverses Robot when Butto 7 on Joystick is Pressed
  DeepSpace/src/main/java/frc/robot/subsystems/Drive.java
Labels: drivetrain, enhancement, good first issue

#23 Gyro Turn
  .metadata/.lock
  .metadata/.plugins/org.eclipse.jdt.core/index.db
  DeepSpace/src/main/java/frc/robot/subsystems/Drive.java
Labels: Automated, drivetrain, enhancement

#47 Added Hatch/Ball mode into teleopPerodic
  DeepSpace/src/main/java/frc/robot/Robot.java
  DeepSpace/src/main/java/frc/robot/TeleopController.java
Labels: Automated, arm, ballintake, hatch, vision
